name: 🧹 Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths-ignore:
      - "CHANGELOG.md"
      - ".release-please-manifest.json"
      - "platformio.ini"

permissions: {}

jobs:
  lint-codebase:
    name: Lint codebase
    uses: equinor/ops-actions/.github/workflows/super-linter.yml@436665154d16356aa4b690ebf43ae41db1b5f8da
    permissions:
      contents: read
      statuses: write
    with:
      filter_regex_exclude: (.*CHANGELOG\.md$|docs/workflows/.*|lib/.*|tools/.*_preview\.html$)
